---
- include_vars: "{{ ansible_os_family }}.yml"

- include: syslog_preparation.yml
  when: marathon_enable_syslog_logging

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: conf.yml tags=configuration

- include: haproxy.yml
  when: haproxy_script_location != ""

- name: Start Marathon service
  service: name=marathon state=restarted enabled=yes 
